var GAME_LEVELS = [
  // ["xxxxx                                                                           ",
  //  "!!!!x                                           oooo                            ",
  //  "xx!!x                                         yyyyyyyyd                         ",
  //  "   v      oo                                 yy      yyd                        ",
  //  "         o y                                yy        yyd                       ",
  //  "        o y yc                             yy          yy       x   x c         ",
  //  "         y   yd             dddddc        yy            yy      x   x y      x  ",
  //  "        y     y            xxxxxxx       yy              yy     xooox        x  ",
  //  "       y       y               xyx                              xyyyx x      x  ",
  //  "   o    y     y                xyx                              x   x x      x  ",
  //  "   o     y   y        oo       xyx                         d    x   x x      x  ",
  //  "   x      y y         xx       xxxxxx                     yyy   x   x x     ox  ",
  //  "  xxx      y      ddxxx                                    y               dox  ",
  //  "!!xxx           cxxxx                                                      dox  ",
  //  "!!xxxx          xxxxx       dddddddddd c                     xxx           xxx  ",
  //  "!!xxx          xxxxxx!!!!!!xxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!xx  ",
  //  "!!xxx @       pxxxxxx!!!!!!!xxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!xx  ",
  //  "!!xxxxxx!!!!!xxxxxxxx!!!!!!!!xxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!xx  ",
  //  "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!!xx!!!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!xx  ",
  //  "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!xx!!!!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!xx  ",
  //  "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
  //  "                                                                                "],
  ["                                                                                                                  ",
   "                         xxxxxxxxxxxxxxyyx                                                                        ",
   "                         xy           xyyxxxxxxxxxx                                                               ",
   "                         xy   p       xxyyyyyyyyyyxx                 d                                            ",
   "                         xy            xxxxxxxxxxyyx                yyy                                           ",
   "                         xy                     xxyx         x     o   o     x                                    ",
   "                         xxxxxxxxy               xyx         x               x                                    ",
   "                         xxxxxxxxy               xyx         x     x   x     x     x                              ",
   "     d                           y       x                   xx             xx     x                              ",
   "     d                           yyyyyyy xc                   xx!!!!!!!!!!!xx      x                              ",
   "   ddddd                                 xx                    xxxx!!!!!xxxx      cxx                             ",
   "  d  d  d                                      x                  xxxxxxx         xx         x                    ",
   "  d  d  d                                      x                                   x         x                    ",
   "  d     d                                      x                                   x         x                    ",
   " y d   d                                       x             d                     xxx       x                    ",
   "    d d                                        xx                                  x         x                    ",
   "     d            o                            x           d   d                   x         x                    ",
   "                 o o         xxxxx  x          x             c                     x         x                    ",
   "   x             o o         x o x  x          x          xxxxxxx            xxxxxxxxxx      x                    ",
   "            xxx   o   xxx    x o x  x          x    xx                   x   x               x                    ",
   "             x         x     x o x  x          xx    x               x   x o x               x                    ",
   "             xyyyyyyyyyx     x o x  x          x     x               x   xxxxx   xxxxxxxxx   x                    ",
   "    x@x      xyyyyyyyyyx     x o x  xx         x     x               x           x           x                    ",
   "!!!!xyx!!!!!!xyyyyyyyyyx!!!!!xx  xx  xx!!!!!!!!xxxx  x!!!!!!!!!!!!!!!x           x   o o     x                    ",
   "!!!!xyx!!!!!!xyyyyyyyyyx!!!!!xx   x   xxvxxvxxvx     x!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxx                    ",
   "!!!!xyx!!!!!!xyyyyyyyyyx!!!!!xx   x                 x!!!!!!!!!!!!!!!!                                             ",
   "!!!!xyx!!!!!!xyyyyyyyyyx!!!!!xxx                    x!!!!!!!!!!!!!!!!                                             ",
   "!!!!xyx!!!!!!xyyyyyyyyyx!!!!!xxxx                  xx!!!!!!!!!!!!!!!!                                             ",
   "!!!!xyx!!!!!!xyyyyyyyyyx!!!!!!xxxxxx               xx!!!!!!!!!!!!!!!!                                             ",
   "!!!!xyx!!!!!!xyyyyyyyyyx!!!!!!!!!xxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!                                             "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
