var GAME_LEVELS = [
  ["xxxxx                                                                           ",
   "!!!!x                                           oooo                            ",
   "xx!!x                                         yyyyyyyyd                         ",
   "          oo                                 yy      yyd                        ",
   "         o y                                yy        yyd                       ",
   "        o y yc                             yy          yy       x   x c         ",
   "         y   yd             dddddc        yy            yy      x   x y      x  ",
   "        y     y            xxxxxxx       yy              yy     xooox        x  ",
   "       y       y               xyx                              xyyyx x      x  ",
   "   o    y     y                xyx                              x   x x      x  ",
   "   o     y   y        oo       xyx                         d    x   x x      x  ",
   "   x      y y         xx       xxxxxx                     yyy   x   x x     ox  ",
   "  xxx      y      ddxxx                                    y                ox  ",
   "!!xxx           cxxxx                                                      dox  ",
   "!!xxxx          xxxxx       dddddddddd                       xxx           xxx  ",
   "!!xxx          xxxxxx!!!!!!xxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!xx  ",
   "!!xxx @p       xxxxxx!!!!!!!xxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!xx  ",
   "!!xxxxxx!!!!!xxxxxxxx!!!!!!!!xxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!xx  ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!!xx!!!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!xx  ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!xx!!!!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!xx  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                "],
  ["                                      x!!x                        xxxxxxx                                    x!x  ",
   "                                      x!!x                     xxxx     xxxx                                 x!x  ",
   "                                      x!!xxxxxxxxxx           xx           xx                                x!x  ",
   "                                      xx!!!!!!!!!!xx         xx             xx                               x!x  ",
   "                                       xxxxxxxxxx!!x         x                                    o   o   o  x!x  ",
   "                                                xx!x         x     o   o                                    xx!x  ",
   "                                                 x!x         x                                xxxxxxxxxxxxxxx!!x  ",
   "                                                 xvx         x     x   x                        !!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!xx            v                        ",
   "                                                               xxxx!!!!!xxxx                                      ",
   "                                               x     x            xxxxxxx        xxx         xxx                  ",
   "                                               x     x                           x x         x x                  ",
   "                                               x     x                             x         x                    ",
   "                                               x     x                             xx        x                    ",
   "                                               xx    x                             x         x                    ",
   "                                               x     x      o  o     x   x         x         x                    ",
   "               xxxxxxx        xxx   xxx        x     x               x   x         x         x                    ",
   "              xx     xx         x   x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "             xx       xx        x o x          x    xx               x   x   x               x                    ",
   "    @ p      x         x        x   x          x     x               x   x   x               x                    ",
   "    xxx      x         x        x   x          x     x               x   xxxxx   xxxxxx      x                    ",
   "    x x      x         x       xx o xx         x     x               x     o     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx !                    xx     xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "]
  // ["                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              "]

  // ["                                                                                                              ",
  //  "         @                                                                                                    ",
  //  "    y     y                                                                                                   ",
  //  "     y   y                                                                                                    ",
  //  "      y y                                                                                                     ",
  //  "                                                                                                              ",
  //  "       x        x             x                                                                               ",
  //  "       x        x             x                                                                               ",
  //  "       x        x             x                                                                               ",
  //  "       x        xx           xx                                                                               ",
  //  "       x         xxxx     xxxx                                                                                ",
  //  "                    xxxxxxx                                                                                   ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              ",
  //  "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
